# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('trial', models.IntegerField(null=True)),
                ('task', models.CharField(max_length=20)),
                ('submit_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'wc_completion_codes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('turk_id', models.CharField(blank=True, max_length=45, null=True)),
                ('paper_id', models.IntegerField(null=True)),
                ('abstract', models.TextField()),
                ('desc', models.CharField(max_length=255)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('trial', models.IntegerField(null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('submit_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'wc_problems',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_word_index', models.IntegerField()),
                ('problem_word_form', models.CharField(max_length=50)),
                ('word_abstraction', models.CharField(blank=True, max_length=10, null=True)),
                ('word_form', models.CharField(max_length=50)),
                ('word_lemma', models.CharField(blank=True, max_length=50, null=True)),
                ('word_sense', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.CharField(max_length=100)),
                ('trial', models.IntegerField(null=True)),
                ('submit_date', models.DateTimeField(null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordclouds.Problem', verbose_name='source problem')),
            ],
            options={
                'db_table': 'wc_synonyms',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='completioncode',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordclouds.Problem', verbose_name='source problem'),
        ),
    ]
