# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordclouds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('trial', models.IntegerField(null=True)),
                ('task', models.CharField(max_length=20)),
                ('submit_date', models.DateTimeField(null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordclouds.Problem', verbose_name='source problem')),
            ],
            options={
                'db_table': 'wc_completion_codes',
                'managed': True,
            },
        ),
    ]
