# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordclouds', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemAttempts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('trial', models.IntegerField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'wc_problems_attempts',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='problem',
            name='paper_id',
        ),
        migrations.AddField(
            model_name='problemattempts',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordclouds.Problem', verbose_name='source problem'),
        ),
    ]
