# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordclouds', '0004_problem_completions'),
    ]

    operations = [
        migrations.AddField(
            model_name='completioncode',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='problemattempts',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
